const data = {
    products:[
        {
            _id :'1',
            name:'gray shirt',
            category:'shirts',
            image:'./images/best_selling_1.jpg',
            price:120,
            countInStock: 20,
            brand: 'pants',
            rating:5,
            numReviews: 10,
            description :'hight quality product',
        },
        {
            _id :'2',
            name:'second shirt',
            category:'shirts',
            image:'./images/best_selling_2.jpg',
            price:100,
            countInStock: 10,
            brand: 'pants',
            rating: 4,
            numReviews: 18,
            description :'hight quality product',
        },
        {
            _id :'3',
            name:'third shirt',
            category:'shirts',
            image:'./images/c_formal_gray_shirt.png',
            price:110,
            countInStock: 5,
            brand: 'pants',
            rating: 3.5,
            numReviews: 15,
            description :'hight quality product',
        },
        {
            _id :'4',
            name:'4th shirt',
            category:'shirts',
            image:'./images/best_selling_3.jpg',
            countInStock: 15,
            price:90,
            brand: 'pants',
            rating: 4.5,
            numReviews: 17,
            description :'hight quality product',
        },
        {
            _id :'5',
            name:'5th shirt',
            category:'shirts',
            image:'./images/on_sale_1.jpg',
            countInStock: 1,
            price:130,
            brand: 'pants',
            rating: 3.6,
            numReviews: 18,
            description :'hight quality product',
        },
        {
            _id :'6',
            name:'6th shirt',
            category:'shirts',
            image:'./images/on_sale_2.jpg',
            countInStock: 1,
            price:150,
            brand: 'pants',
            rating:  5,
            numReviews: 17,
            description :'hight quality product',
        },
    ],
};
export default data;